CREATE USER codeloop WITH PASSWORD 'codeloop';
ALTER USER codeloop WITH SUPERUSER;

CREATE DATABASE codeloop;
CREATE DATABASE codeloop_test;

GRANT ALL PRIVILEGES ON DATABASE codeloop TO codeloop;
GRANT ALL PRIVILEGES ON DATABASE codeloop_test TO codeloop;
